kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: example-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
    - description: 'Expected output'
      name: EXPECTED_OUTPUT
      default: "Hello World!"
      type: string
    # - description: 'Crucible controller address'
    #   name: 'CPT_CONTROLLER_SECRET'
    #   type: string
    #   default: cpt-controller
  tasks:
    - name: hello-world
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          script: |
            dnf -y install jq
            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
            # Run custom tests for the given Snapshot here
            # After the tests finish, record the overall result in the RESULT variable
            RESULT="SUCCESS"

            # Output the standardized TEST_OUTPUT result in JSON form
            TEST_OUTPUT=$(jq -rc --arg date $(date -u --iso-8601=seconds) --arg RESULT "${RESULT}" --null-input \
              '{result: $RESULT, timestamp: $date, failures: 0, successes: 1, warnings: 0}')
            echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)

    - name: hello-crucible
      description: reach out to crucible controller
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        # - name: cpt_controller
        #   value: $(params.CPT_CONTROLLER_SECRET)
      taskSpec:
        volumes:
          - name: crucible-controller-id
            secret:
              optional: true
              secretName: crucible-controller-id
        #   - name: cpt-controller
        #     secret:
        #       optional: true
        #       secretName: $(params.cpt_controller)       
        params:
          - name: SNAPSHOT
          # - name: cpt_controller
        steps:
        - name: controller-login
          image: registry.redhat.io/openshift4/ose-cli:latest
          volumeMounts:
            - mountPath: /etc/secrets
              name: crucible-controller-id
              readOnly: true
          env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            - name: CONTROLLER_PASSWORD
              # value: $(params.cpt_controller.password)
              valueFrom:
                secretKeyRef:
                  name: cpt-controller
                  key: password
            - name: CONTROLLER_USER
              # value: $(params.cpt_controller.user)
              valueFrom:
                secretKeyRef:
                  name: cpt-controller
                  key: user
            - name: CONTROLLER_ADDRESS
              # value: $(params.cpt_controller.address)
              valueFrom:
                secretKeyRef:
                  name: cpt-controller
                  key: address
            - name: MY_FIRST_SECRET_robot
              valueFrom:
                secretKeyRef:
                  name: my-first-secret
                  key: robot
            - name: MY_FIRST_SECRET_address
              valueFrom:
                secretKeyRef:
                  name: my-first-secret
                  key: address                  
          script: |    
            echo ${MY_FIRST_SECRET_robot}
            echo ${MY_FIRST_SECRET_address}
            dnf -y install sshpass openssh
            # sshpass -p "${CONTROLLER_PASSWORD}" ssh ${CONTROLLER_USER}@${CONTROLLER_ADDRESS} 'pwd; ls -alh; uname -n; uname -v;'
            /usr/bin/ssh -i /etc/secrets/konflux_crucible_id ${CONTROLLER_USER}@${CONTROLLER_ADDRESS} 'pwd; ls -alh; uname -n; uname -v;'
